// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChe3EA5Vj45L6ii2TTRHiWWR9OYmvSm1A',
    appId: '1:264936141908:android:2c735bd8cafaf6cced29c1',
    messagingSenderId: '264936141908',
    projectId: 'bluesky--gallery-app',
    storageBucket: 'bluesky--gallery-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk3I0pBx63cQnmLmN45k7qlGxrJ6fyQzQ',
    appId: '1:264936141908:ios:fb712faf30ac15c0ed29c1',
    messagingSenderId: '264936141908',
    projectId: 'bluesky--gallery-app',
    storageBucket: 'bluesky--gallery-app.appspot.com',
    iosClientId: '264936141908-hdktngboe8qjsotefq36eten9nd0nip2.apps.googleusercontent.com',
    iosBundleId: '3',
  );
}
